export const DETECTION = {
  // Method 1: Presence Subscription
  PRESENCE_RESUBSCRIBE_INTERVAL_MS: parseInt(process.env.PRESENCE_RESUBSCRIBE_INTERVAL_MS || '240000'), // 4 min
  PRESENCE_POLL_INTERVAL_MS: parseInt(process.env.PRESENCE_POLL_INTERVAL_MS || '30000'), // 30s
  PRESENCE_STAGGER_BASE_MS: 500,

  // Method 2: RTT Probing
  RTT_PROBE_INTERVAL_MS: parseInt(process.env.RTT_PROBE_INTERVAL_MS || '8000'), // 8s
  RTT_TIMEOUT_MS: parseInt(process.env.RTT_TIMEOUT_MS || '10000'), // 10s
  RTT_HISTORY_SIZE: 2000,
  RTT_MOVING_AVG_WINDOW: 3,
  RTT_ACTIVE_THRESHOLD_FACTOR: 0.9,

  // Method 3: Behavioral
  PROFILE_PIC_POLL_INTERVAL_MS: 30 * 60 * 1000, // 30 min

  // Confidence Engine
  CONFIDENCE_THRESHOLD_ONLINE: parseInt(process.env.CONFIDENCE_THRESHOLD_ONLINE || '70'),
  CONFIDENCE_DECAY_PER_MINUTE: 0.05,
  CONFIDENCE_DECAY_START_MINUTES: 2,
  STATUS_HYSTERESIS_MS: parseInt(process.env.STATUS_HYSTERESIS_MS || '15000'), // 15s
  SNAPSHOT_INTERVAL_MS: 30_000, // 30s

  // Signal weights
  WEIGHT_PRESENCE_AVAILABLE: 0.40,
  WEIGHT_RTT_ACTIVE: 0.35,
  WEIGHT_BEHAVIORAL: 0.25,
  WEIGHT_PRESENCE_UNAVAILABLE: -0.20,
  WEIGHT_RTT_OFFLINE: -0.35,
  WEIGHT_NO_SIGNAL_DECAY: -0.15,
} as const;

export const SESSION = {
  RECONNECT_INITIAL_MS: 1000,
  RECONNECT_MAX_MS: 60_000,
  RECONNECT_MULTIPLIER: 2,
  MAX_RECONNECT_ATTEMPTS: 20,
  HEALTH_CHECK_INTERVAL_MS: 30_000,
  MAX_TARGETS_PER_SESSION: 50,
  WARMUP_PERIOD_HOURS: 48,
} as const;

export const RATE_LIMIT = {
  MAX_SUBSCRIPTIONS_PER_SECOND: 5,
  MAX_PROBES_PER_MINUTE_PER_SESSION: 100,
  RATE_LIMIT_BACKOFF_MS: 5 * 60 * 1000, // 5 min
} as const;

export const DATA_RETENTION = {
  RAW_EVENT_RETENTION_DAYS: 30,
  AGGREGATED_RETENTION_DAYS: 365,
} as const;
